[package]
name = "mag_core"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
epimetheus-methylome = "1.1.0"
polars = { version = "0.52.0", features = ["full"] }
tempfile = "3.24.0"
thiserror = "2.0.17"
